plugins {
	id 'org.jetbrains.kotlin.jvm' version '1.9.25'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.9.25'
	id 'war'
	id 'org.springframework.boot' version '3.2.12'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.thinkimi.gradle.MybatisGenerator' version '2.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	implementation 'org.mybatis.dynamic-sql:mybatis-dynamic-sql:1.5.0'
	implementation 'org.springframework.boot:spring-boot-starter-validation' // バリデーション
	// implementation 'org.springframework.boot:spring-boot-starter-security'   // SpringSecurity
	runtimeOnly 'org.postgresql:postgresql:42.7.1'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test:3.2.3'
	testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.1'
	testImplementation 'com.ninja-squad:springmockk:4.0.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
	testImplementation 'com.h2database:h2'  // テスト用DB
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll '-Xjsr305=strict'
	}
}

tasks.withType(Test) {
	useJUnitPlatform()
}

mybatisGenerator {
	verbose = true
	configFile = "${projectDir}/src/main/resources/generatorConfig.xml"
	mybatisProperties = [
		'driverFile'     : "$projectDir/src/main/libs/postgresql-42.7.1.jar",
		'jdbcUrl'        : "jdbc:postgresql://localhost:5432/emp-management-restapi",
		'jdbcDriverClass': 'org.postgresql.Driver',
		'jdbcUsername'   : 'postgres',
		'jdbcPassword'   : 'postgres'
	]
}
