spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ex-emp-api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration: 
    map-underscore-to-camel-case: true
