### 管理者一覧表示
Get http://localhost:8080/administrators HTTP/1.1

### 管理者id検索
GET http://localhost:8080/administrators/3 HTTP/1.1

### 例外
GET http://localhost:8080/administrators/5 HTTP/1.1

### 管理者登録
POST  http://localhost:8080/administrators HTTP/1.1
content-type: application/json

{    
    "name": "管理者三四郎",
    "mailAddress": "testadmin@example.com",
    "password": "testtest34"
}


### 管理者削除
DELETE http://localhost:8080/administrators/3 HTTP/1.1

### 管理者更新
PUT http://localhost:8080/administrators/3 HTTP/1.1
content-type: application/json

{    
    "name": "管理者さんしろう",
    "mailAddress": "update_admin@example.com",
    "password": "updatetest34"
}
